version: "3"

services:
  server:
    image: cz.cvut.fit/tracker-server:1.0
    ports:
      - 8085:8080
    environment:
      - JWT_SECRET=mH@6@*6dp*p^8Xhegecv
      - JWT_EXPIRATION=86400
      - DB_JDBC_URL=jdbc:h2:/DB/tracker;INIT=RUNSCRIPT FROM './create.sql';MODE=MySQL
      - DB_USERNAME=
      - DB_PASSWORD=
      - MQTT_HOST=mqtt
      - MQTT_PORT=8883
      - MQTT_TOPIC=sledovac
      - MQTT_SSL=true
      - MQTT_SUBSCRIBER_NAME=tracker-rpi
      - FRONTEND_DIR=/front/
    volumes:
      - ~/DB:/DB
      - ~/front:/front
    restart: always

