version: "3"

services:
  server:
    image: jehlima2/tracker-server:1.0
    ports:
      - 8085:8080
    environment:
      - JWT_SECRET="mH@6@*6dp*p^8Xhegecv"
      - JWT_EXPIRATION=600
      - DB_JDBC_URL=jdbc:h2:/DB/docker;MODE=MySQL
      - DB_USERNAME=
      - DB_PASSWORD=
    volumes:
    - /home/dizider/DB:/DB
